### ISSUE TITLE
Beschreibungsfeld - Formatierungen ermöglichen

### ISSUE THREAD

**Issue by AgentCT** [gfg-development/linkslist#1]
Hallo,

im Feld "Beschreibung" ist bisher leider nur die Eingabe von Text möglich. Es wäre schön, wenn man den Text in diesem Feld auch formatieren könnte.

Vielen Dank

**Comment by gfg-development** [comment]
Hallo,

vielen Dank für die Anregung. Ich habe die Formatierungsmöglichkeiten in der Version 1.3.0 für die Beschreibung erweitert.
